M [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js' Require stack: - /home/user/studio/frontend/node_modules/@babel/types/lib/index.js - /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js - /home/user/studio/frontend/node_modules/@babel/core/lib/index.js   Plugin: vite:react-babel   File: /home/user/studio/frontend/src/main.jsx Error: The following dependencies are imported but could not be resolved:
  @/App (imported by /home/user/studio/frontend/src/main.jsx)
  @/styles/index.css (imported by /home/user/studio/frontend/src/main.jsx)

Are they installed?
    at file:///home/user/studio/frontend/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:18202:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/user/studio/frontend/node_modules/vite/dist/node/chunks/dep-B0fRCRkQ.js:52234:28
4:07:53 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx
4:07:54 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx (x2)
4:07:54 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx (x3)
4:07:54 AM [vite] Internal server error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx
      at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
      at Module._load (node:internal/modules/cjs/loader:1051:27)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
      at require (node:internal/modules/helpers:179:18)
      at Object.<anonymous> (/home/user/studio/frontend/node_modules/@babel/types/lib/index.js:416:25)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32)
      at Module._load (node:internal/modules/cjs/loader:1104:12)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
4:07:57 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx
4:07:58 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx (x2)
4:07:58 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx (x3)
4:07:58 AM [vite] Internal server error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx
      at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
      at Module._load (node:internal/modules/cjs/loader:1051:27)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
      at require (node:internal/modules/helpers:179:18)
      at Object.<anonymous> (/home/user/studio/frontend/node_modules/@babel/types/lib/index.js:416:25)
      at Module._compile (node:internal/modules/cjs/loader:1469:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
      at Module.load (node:internal/modules/cjs/loader:1288:32)
      at Module._load (node:internal/modules/cjs/loader:1104:12)
      at Module.require (node:internal/modules/cjs/loader:1311:19)
4:08:00 AM [vite] Pre-transform error: Cannot find module './validators/react/isReactComponent.js'
Require stack:
- /home/user/studio/frontend/node_modules/@babel/types/lib/index.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/transformation/file/file.js
- /home/user/studio/frontend/node_modules/@babel/core/lib/index.js
  Plugin: vite:react-babel
  File: /home/user/studio/frontend/src/main.jsx